"""
SQL Agent using LangGraph - Converts natural language to PostgreSQL queries
and runs them on a Neon database.
"""

import os
import re
from dotenv import load_dotenv
from typing import TypedDict
from sqlalchemy import create_engine, text
from langchain_community.utilities import SQLDatabase
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END

                       
load_dotenv(dotenv_path=os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".env"))

                        
Database_URL = (
    os.environ.get("Databaseurl")
    or os.environ.get("DATABASE_URL")
    or os.environ.get("POSTGRES_URL")
)
if Database_URL:
    engine = create_engine(Database_URL, connect_args={"connect_timeout": 10}, pool_pre_ping=True)
    db = SQLDatabase(engine)
else:
    engine = None
    db = None
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)


def ensure_read_only_sql(sql_query: str) -> None:
    """Allow a single SELECT/CTE statement and reject potentially mutating SQL.

    The statement is generated by an LLM, so it must be treated as untrusted even
    though the database is used only for analytics.
    """
    without_comments = re.sub(r"/\*.*?\*/|--[^\r\n]*", " ", sql_query, flags=re.DOTALL)
    without_literals = re.sub(r"'(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"", " ", without_comments)
    statements = [part.strip() for part in without_literals.split(";") if part.strip()]
    if len(statements) != 1 or not re.match(r"^(SELECT|WITH)\b", statements[0], re.IGNORECASE):
        raise ValueError("Only a single read-only SELECT query is allowed.")

    forbidden = r"\b(INSERT|UPDATE|DELETE|ALTER|DROP|CREATE|GRANT|REVOKE|TRUNCATE|MERGE|CALL|COPY|VACUUM)\b"
    if re.search(forbidden, statements[0], re.IGNORECASE):
        raise ValueError("Only a single read-only SELECT query is allowed.")


                                                                   
class AgentState(TypedDict):
    question: str
    schema_info: str
    sql_query: str
    query_result: str
    final_answer: str


                                                                                
def get_schema(state: AgentState):
    if db is None:
        raise ValueError("DATABASE_URL environment variable is not set.")
    schema_info = db.get_table_info()
    print("got the schema")
    return {"schema_info": schema_info}


                                                                           
def generate_sql(state: AgentState):
    prompt = f"""You are a PostgreSQL expert. Based on the database schema below,
write a SQL query that answers the user's question.

Rules:
- Only return the SQL query, nothing else
- Use double quotes for column names with uppercase letters
- Do NOT use LIMIT unless the user explicitly asks for a specific number of results. Retrieve all matching data.

Schema:
{state["schema_info"]}

Question: {state["question"]}

SQL:"""

    response = llm.invoke(prompt)
    sql_query = response.content.strip()
    print(f"generated query: {sql_query}")
    return {"sql_query": sql_query}


                                                     
def execute_query(state: AgentState):
    try:
        ensure_read_only_sql(state["sql_query"])
        with engine.connect() as conn:
            result = conn.execute(text(state["sql_query"]))
            rows = result.fetchall()
            columns = list(result.keys())

            if not rows:
                query_result = "no results found"
            else:
                                                         
                header = " | ".join(columns)
                data = "\n".join(
                    " | ".join(str(val) for val in row) for row in rows
                )
                query_result = f"{header}\n{data}"

        print(f"query ran successfully, got {len(rows)} rows")
    except Exception as e:
        print(f"query failed: {e}")
        raise Exception(f"Database Execution Failed: {str(e)}")

    return {"query_result": query_result}


                                                                
def format_answer(state: AgentState):
    prompt = f"""Based on the question and query result below, give a short clear answer.

Question: {state["question"]}
SQL Query: {state["sql_query"]}
Result:
{state["query_result"]}

Answer:"""

    response = llm.invoke(prompt)
    return {"final_answer": response.content.strip()}


                                 
                                                                         
workflow = StateGraph(AgentState)

workflow.add_node("get_schema", get_schema)
workflow.add_node("generate_sql", generate_sql)
workflow.add_node("execute_query", execute_query)
workflow.add_node("format_answer", format_answer)

workflow.add_edge(START, "get_schema")
workflow.add_edge("get_schema", "generate_sql")
workflow.add_edge("generate_sql", "execute_query")
workflow.add_edge("execute_query", "format_answer")
workflow.add_edge("format_answer", END)

graph = workflow.compile()


                   
if __name__ == "__main__":
    question = "Who is the customer who had the most orders?"
    print(f"\nQuestion: {question}\n")

    result = graph.invoke({"question": question})

    print(f"\nAnswer: {result['final_answer']}")
